name: deploy_frontend

on:
  push:
    branches:
      - master
    paths: "client_react/**"

jobs:
  # This job will:
  #   * deploy a production build every time there is a push only on the master branch
  #   * comment that commit with the deploy URL
  publishMasterCommit:
    name: Publish to Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      # ... your other build steps to produce a build directory
      # e.g. `yarn build` for create-react-app

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: npm install --prefix client_react

      - name: Build page
        run: npm run client_prod

      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: "./client_react/build"
          comment-on-commit: true
